spring:
  application:
    name: mybatis-plus-code-generator
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**

logging:
  level:
#    root: debug
    com.fengwenyi: debug
    com.baomidou: debug

erwin:
  # 启动方式：jar / docker
  start-method: jar
